# GdUnit4 test: TerminalView escapes both [ and ] in user text to prevent BBCode injection.
#
# Covers: Escaping literal [ and ] characters from shell output so they don't interfere
#         with BBCode tags generated by the ANSI parser.
#
# Bug context: Starship prompt segments like [segment] or text ending with ] can create
#              malformed BBCode like `[/bgcolor]]` when concatenated with BBCode closing tags,
#              causing the RichTextLabel BBCode parser to fail and display tags as literal text.
#
# All tests run in mock mode -- no GDExtension required.
extends GdUnitTestSuite

const TERMINAL_SCENE := preload("res://scenes/terminal.tscn")

var _view: TerminalView


func before_test() -> void:
	TerminalManager.is_mock_mode = true
	TerminalManager.is_addon_available = false
	TerminalManager._mock_output_buffer.clear()
	_view = TERMINAL_SCENE.instantiate() as TerminalView
	add_child(_view)


func after_test() -> void:
	if is_instance_valid(_view):
		_view.queue_free()
	_view = null


# ---------------------------------------------------------------------------
# Basic bracket escaping
# ---------------------------------------------------------------------------


func test_left_bracket_is_escaped() -> void:
	SignalBus.output_ready.emit("[test]")
	await get_tree().process_frame
	var bbcode := _view._output_accumulator
	# [ should be escaped to [lb]
	assert_str(bbcode).contains("[lb]test")


func test_right_bracket_is_escaped() -> void:
	SignalBus.output_ready.emit("[test]")
	await get_tree().process_frame
	var bbcode := _view._output_accumulator
	# ] should be escaped to [rb]
	assert_str(bbcode).contains("test[rb]")


func test_both_brackets_are_escaped() -> void:
	SignalBus.output_ready.emit("[text]")
	await get_tree().process_frame
	var bbcode := _view._output_accumulator
	assert_str(bbcode).is_equal("[lb]text[rb]")


# ---------------------------------------------------------------------------
# Bracket escaping with ANSI color codes
# ---------------------------------------------------------------------------


func test_bracket_after_color_reset() -> void:
	var esc := char(27)
	# Pattern: color, then ], then reset.
	# This used to create `[/color]]` which breaks BBCode parsing.
	SignalBus.output_ready.emit(esc + "[32mtext]" + esc + "[0m")
	await get_tree().process_frame
	var bbcode := _view._output_accumulator
	# Should have:  [color=...]text[rb][/color]
	# NOT:          [color=...]text][/color]  (malformed)
	assert_str(bbcode).contains("text[rb]")
	# Malformed BBCode would have unescaped ] followed by [, like "text][/color]"
	# Valid: "text[rb][/color]" - the [rb] is the escape
	# Check specifically for the malformed pattern
	assert_bool(bbcode.contains("text][/")).is_false()


func test_bracket_before_bgcolor() -> void:
	var esc := char(27)
	# Pattern: [, then background color.
	# Unescaped [ could open a phantom BBCode tag.
	SignalBus.output_ready.emit("[" + esc + "[44mtext" + esc + "[0m")
	await get_tree().process_frame
	var bbcode := _view._output_accumulator
	# Should have: [lb][bgcolor=...]text[/bgcolor]
	assert_str(bbcode).contains("[lb][bgcolor=")


func test_starship_segment_pattern() -> void:
	var esc := char(27)
	# Simulate a Starship prompt segment: [bgcolor][/bgcolor]
	# Actual Starship outputs something like: ^[[44m❯^[[0m]  (blue background, arrow, reset, ])
	SignalBus.output_ready.emit(esc + "[44m>" + esc + "[0m]")
	await get_tree().process_frame
	var bbcode := _view._output_accumulator
	# Should have: [bgcolor=...]>[/bgcolor][rb]
	# NOT:         [bgcolor=...]>[/bgcolor]]  (malformed)
	assert_str(bbcode).contains("[/bgcolor][rb]")
	assert_bool(bbcode.contains("[/bgcolor]]")).is_false()


# ---------------------------------------------------------------------------
# Edge cases
# ---------------------------------------------------------------------------


func test_double_bracket() -> void:
	SignalBus.output_ready.emit("[[")
	await get_tree().process_frame
	var bbcode := _view._output_accumulator
	assert_str(bbcode).is_equal("[lb][lb]")


func test_mixed_brackets_and_text() -> void:
	SignalBus.output_ready.emit("a[b]c")
	await get_tree().process_frame
	var bbcode := _view._output_accumulator
	assert_str(bbcode).is_equal("a[lb]b[rb]c")


func test_bracket_at_end_of_colored_text() -> void:
	var esc := char(27)
	# Red text ending with ], then reset.
	SignalBus.output_ready.emit(esc + "[31mERROR]" + esc + "[0m")
	await get_tree().process_frame
	var bbcode := _view._output_accumulator
	# Should have: [color=red]ERROR[rb][/color]
	assert_str(bbcode).contains("ERROR[rb]")
	# The literal "ERROR]" (without [rb] escape) should not appear
	assert_bool(bbcode.contains("ERROR]") and not bbcode.contains("ERROR[rb]")).is_false()


func test_multiple_brackets_in_sequence() -> void:
	SignalBus.output_ready.emit("]]]")
	await get_tree().process_frame
	var bbcode := _view._output_accumulator
	assert_str(bbcode).is_equal("[rb][rb][rb]")


# ---------------------------------------------------------------------------
# Verify BBCode is valid after escaping
# ---------------------------------------------------------------------------


func test_escaped_brackets_do_not_break_bbcode_parsing() -> void:
	var esc := char(27)
	# Complex case: color, bracket, reset, bracket.
	SignalBus.output_ready.emit(esc + "[32m[test]" + esc + "[0m]end")
	await get_tree().process_frame
	var bbcode := _view._output_accumulator
	# Should parse cleanly in RichTextLabel (no visible BBCode tags in parsed output).
	# We can't easily test RichTextLabel parsing here, but we can verify the BBCode structure:
	# - All BBCode tags are properly closed.
	# - No stray ] characters outside [rb] escapes.
	var open_color := bbcode.count("[color=")
	var close_color := bbcode.count("[/color]")
	assert_int(open_color).is_equal(close_color)
	# Verify that literal ] is escaped.
	# Count unescaped ] by looking for patterns like "text]" (not "[rb]").
	# Since all ] should be escaped, the only ] should be in [/color], [/bgcolor], [rb].
	# A quick heuristic: bbcode should not contain "t]" (text followed by unescaped ]).
	assert_bool(bbcode.contains("t]")).is_false()  # 'test]' pattern
	assert_bool(bbcode.contains("d]")).is_false()  # 'end]' pattern


# ---------------------------------------------------------------------------
# Compound SGR sequences (bgcolor + fgcolor in one escape)
# ---------------------------------------------------------------------------


func test_compound_sgr_bgcolor_then_fgcolor_produces_balanced_tags() -> void:
	var esc := char(27)
	# Starship sends compound sequences: set bgcolor AND fgcolor in a single escape.
	# e.g. ESC[48;2;214;93;14;38;2;251;241;199m (set bg orange, fg cream in one seq).
	# Old one-pass code generated: [color=orange][bgcolor=orange][/color][color=cream]
	# which has an orphaned [/color] (no matching open between [bgcolor] and it).
	SignalBus.output_ready.emit(
		esc + "[38;2;214;93;14m" + esc + "[48;2;214;93;14;38;2;251;241;199mhello" + esc + "[0m"
	)
	await get_tree().process_frame
	var bbcode := _view._output_accumulator
	# Tags must balance.
	var open_color2 := bbcode.count("[color=")
	var close_color2 := bbcode.count("[/color]")
	assert_int(open_color2).is_equal(close_color2)
	var open_bg := bbcode.count("[bgcolor=")
	var close_bg := bbcode.count("[/bgcolor]")
	assert_int(open_bg).is_equal(close_bg)


func test_compound_sgr_no_orphaned_closing_tags() -> void:
	var esc := char(27)
	# After a compound sequence that changes both bg and fg, a plain reset (ESC[0m)
	# should close everything cleanly with no leftover closing tags.
	SignalBus.output_ready.emit(esc + "[48;2;100;100;100;38;2;200;200;200mtext" + esc + "[0m")
	await get_tree().process_frame
	var bbcode := _view._output_accumulator
	# Should end cleanly -- no closing tags emitted when nothing is open.
	var open_color3 := bbcode.count("[color=")
	var close_color3 := bbcode.count("[/color]")
	assert_int(open_color3).is_equal(close_color3)
	var open_bg2 := bbcode.count("[bgcolor=")
	var close_bg2 := bbcode.count("[/bgcolor]")
	assert_int(open_bg2).is_equal(close_bg2)
